// <auto-generated />
namespace TrueCosmetics.BootstrapApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class OrderModuleAddetToCotext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderModuleAddetToCotext));
        
        string IMigrationMetadata.Id
        {
            get { return "201701121251568_OrderModuleAddetToCotext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
